FROM python:3.8-slim

WORKDIR /app

COPY src/requirements.txt .

RUN pip install -r requirements.txt

COPY src/request_book.py .

# Especifica el comando a ejecutar al iniciar el contenedor
CMD ["python", "request_book.py"]
